baseURL = "https://googolxx.github.io/"
languageCode = 'zh-cn'
title = "Renjie's log"
theme = 'ananke'



[params]
  math = true
  custom_css = ["custom.css"]
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
          
[markup.goldmark.renderer]
unsafe = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"