baseURL = 'https://googolxx.github.io/Renjie/'
languageCode = 'zh-cn'
title = 'Renjie Zou blog list'
theme = 'ananke'


[params]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[caches]
  [caches.images]
    dir = ":cacheDir/images"